apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: payment
  namespace: roboshop
spec: 
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      component: payment 
      tier: app 
  template:
    metadata:
      labels:
        project: roboshop
        component: payment
        tier: app 
    spec:
      containers:
      - name: payment 
        image: "{{ .Values.deployment.image_URL }}:{{ .Values.deployment.imageVersion }}"
        envFrom:
          - configMapRef:
              name: payment-cm 
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"