apiVersion: v1 
kind: Service 
metadata:
  name: frontend 
  namespace: roboshop
spec:
  type: LoadBalancer 
  selector:
    project: roboshop
    component: frontend
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80